version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localhost:8000
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    depends_on:
      - dynamodb
    volumes:
      - ./server:/usr/src/app
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - dynamodb_data:/home/dynamodblocal/data # Persist data in a Docker volume

volumes:
  dynamodb_data: